apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-3
  namespace: devops
spec:
  containers:
  - name: nginx-c
    image: nginx:1.15.2
    ports:
    - containerPort: 80
  - name: redis-c
    image: redis
    ports:
    - containerPort: 6379
