apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      name: front-pod
      labels:
        app: httpd
    spec:
      containers:
      - name: front
        image: httpd:2.4-alpine
